
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: redis
    image: redis
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
  - name: alternate
    image: redis
    ports:
    - containerPort: 6378